In [8]:
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np

In [9]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

In [10]:
sentences = [
    "The cat sat on the mat.",
    "The dog slept on the floor.",
    "I love natural language processing."
]

# Embedding (CLS)

In [11]:
def get_embeddings(sentences, model, tokenizer):
    encoded_input = tokenizer(sentences, padding = True, truncation = True, return_tensors = 'pt')
    with torch.no_grad():
        model_output = model(**encoded_input)

    sentence_embeddings = model_output.last_hidden_state[:, 0,:]

    return sentence_embeddings.numpy()

In [12]:
embeddings = get_embeddings(sentences, model, tokenizer)
print(f"Embedding shape: {embeddings.shape}")
print(f"First 5 dimensions of the sentences' embeddings:\n{np.round(embeddings[:, :5], 3)}")

Embedding shape: (3, 768)
First 5 dimensions of the sentences' embeddings:
[[-0.364 -0.053 -0.367 -0.03  -0.461]
 [-0.276 -0.043 -0.613  0.175 -0.309]
 [-0.042  0.043 -0.253 -0.35  -0.374]]


# Embedding (Mean Pooling)
Instead of relying solely on the <b>[CLS]</b> token embedding to represent a sentence, one can also use <b>mean pooling</b>, which <b>averages the embeddings of all output tokens</b>. This approach often yields a more balanced and comprehensive representation of the sentence.

In [13]:
def get_embeddings(sentences, model, tokenizer):
    encoded_input = tokenizer(sentences, padding=True, truncation=True,return_tensors='pt')
    with torch.no_grad():
        model_output = model(**encoded_input)